services:
  database:
    image: 'postgres:16-alpine'
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./node_modules/connect-pg-simple/table.sql:/docker-entrypoint-initdb.d/01-session.sql:ro
      - ./src/server/sql/20210525 init.sql:/docker-entrypoint-initdb.d/02-init.sql:ro
      - ./src/server/sql/20210602 json.sql:/docker-entrypoint-initdb.d/03-json.sql:ro
